site_name: Choeur d'ailleurs
site_description: Chants du monde.
#copyright: Copyright &copy; 2019-2020 <a href="https://www.grame.fr">Grame-CNCM</a>
nav:
    - Calendrier: cal.md
    - Documents: docs.md
    - Photos: photos.md
    - Contacts: contacts.md

theme: 
    name: mkdocs
    locale: fr
    logo: rsrc/logo.png

site_dir: ../docs

#extra:

plugins:
    - search
    
extra_javascript:
  - 'rsrc/addon.js'

extra_css:
   - 'style.css'
